server:
  port: 8082


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: article-app
        uri: http://localhost:8083/
        predicates:
        - Path=/article/**